### ISSUE TITLE
issue with netscaler converter

### ISSUE THREAD

**Issue by wewenttothemoon** [vmware/alb-sdk#1829]
hello, reaching out because we are trying to use the netscaler converter script on an exported netscaler conf file but we are running into issues. When we run the tool netsacer_converter.py it fails because no module named netscaler_converter exists. Upon trying to install the tools using pip install avimigrationtools==17.1.1.post1 avisdk==17.1.1.post1 it fails everytime (on multiple pcs) when trying to install pycrypto.. Even when when trying to install pycrypto using pip install same error results. Tried on latest python release and older one 2.7. have PIP and setuptools up to date. Please see attached output when trying to install avisdk / avimigrationtools
[pycryptofailure.txt](https://github.com/vmware/alb-sdk/files/7509795/pycryptofailure.txt)

**Comment by chaitanyaavi** [comment]
@wewenttothemoon 
This looks like environment issue to install pycrypto You can put this to pycrypto lib.
We recommend to use Python 3 for the latest migration tools also to avoid these local environment issues we have a docker image where all dependancies are installed and preset. 
https://hub.docker.com/repository/registry-1.docker.io/avinetworks/avitools/builds/95d8ef47-ef78-4819-876f-c8d25c58968c
