### ISSUE TITLE
Error when copying a WAF policy between two clusters

### ISSUE THREAD

**Issue by DoktorByte** [vmware/alb-sdk#2621]
### Describe the bug

When we try to copy a WAF policy between two AVI clusters, we get the following error:

$ python3 clone_vs.py -c C1 -dc C2 -t Tenant -2t Tenant generic wafpolicy Repo Repo-clonetest
clone_vs.py version 2.0.2

Password for admin@C1:
Password for admin@C2:
Creating source API session to C1...OK!

Creating destination API session to C2...OK!

Detected API version 22.1.2. Reconnecting.

Creating source API session to C1 (22.1.2)...OK!

Creating destination API session to C2 (22.1.2)...OK!

Trying to clone object of type wafpolicy with name Repo [Tenant] to Repo-clonetest [Tenant]...

Unable to clone wafpolicy "Repo" as "Repo-clonetest" (400:{"error": "Invalid configuration: WafPolicy application signature provider not found."})
=> Unable to clone wafpolicy "Repo" as "Repo-clonetest"

-----------------------------------------------------

Copying the WAF policy within the same AVI cluster works without problems:

$ python3 clone_vs.py -c C1 -dc C1 -t Tenant -2t Tenant generic wafpolicy Repo Repo-clonetest
clone_vs.py version 2.0.2

Password for admin@C1:
Password for admin@C1:
Creating source API session to C1...OK!

Creating destination API session to C1...OK!

Detected API version 22.1.2. Reconnecting.

Creating source API session to C1 (22.1.2)...OK!

Creating destination API session to C1 (22.1.2)...OK!

Trying to clone object of type wafpolicy with name Repo [Tenant] to Repo-clonetest [Tenant]...
OK!

New object of type wafpolicy created as follows:
      Name: Repo-clonetest
    Tenant: Tenant

--------------------------------
Actions taken were:
 1. Cloned wafpolicy "Repo" in tenant "Tenant" to "Repo-clonetest" in tenant "Tenant"

### Reproduction steps

python3 clone_vs.py -c C1 -dc C2 -t Tenant -2t Tenant generic wafpolicy wafpolicy wafpolicy-clone

### Expected behavior

I would have expected that you can copy a WAF policy not only in the same cluster, but also to other clusters.

**Comment by thebertster** [comment]
Thanks for raising this. Please note that this script is provided as a example only and does not claim to be a fully-supported or comprehensive tool, especially for cross-cloud and cross-Controller scenarios (as noted in the README). However this particular issue will be addressed in a future update. Please check the development branch which should now have an update for this scenario (https://github.com/vmware/alb-sdk/tree/rc-clone_vs_refactoring/python/avi/sdk/samples).
