### ISSUE TITLE
Apisession throwing 401 error

### ISSUE THREAD

**Issue by abhimukherjee91** [vmware/alb-sdk#926]
Hi, I am very new to python and was trying to use avisdk to fetch some config from AVI vantage controller. After importing the repository on my venv in pycharm, when I am trying to establish a session, I am getting the 401 unauthorized error. I am using the below command,

api = ApiSession.get_session("controller_ip", "username", "password")

Would it be possible for someone to help me out.

**Comment by ericsysmin** [comment]
@abhimukherjee91 did you ever figure it out?
